//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo_Raph
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Especes()
        {
            this.Animaux = new HashSet<Animaux>();
        }
    
        public string EspeceAnimal { get; set; }
        public Nullable<int> Nombre_de_spécimène { get; set; }
        public string Classe { get; set; }
        public string Famille { get; set; }
        public string Sous_famille { get; set; }
        public string régime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animaux> Animaux { get; set; }
    }
}
